# https://doc.rust-lang.org/cargo/reference/profiles.html

[workspace]
members = [
  "console",
  "editor",
  "firstperson",
  "game",
  "testgame",
  "launcher",
  "menutest",
  "network",
  "physics",
  "scripting"
]
# exclude = ["crates/foo", "path/to/other"]

# https://bevyengine.org/learn/book/getting-started/setup/
resolver = "2" # path reslove packages

# Enable a small amount of optimization in debug mode
# [profile.dev]
# opt-level = 1

# Optimize the engine in debug builds, but leave project's code non-optimized.
# By using this technique, you can still debug you code, but engine will be fully
# optimized and debug builds won't be terribly slow. With this option, you can 
# compile your game in debug mode, which is much faster (at least x3), than release.
# [profile.dev.package."*"]
# opt-level = 3

#[dependencies]
# windows > dynamic - does not work 65535 objects exceeded
# bevy = {version = "0.9", features = ["dynamic"]}
# bevy = {version = "0.9", features = []}
