[package]
name = "scripting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy_console = "0.6.0"
bevy_mod_scripting = "0.2.1"

